baseURL = 'https://sevenslegals.netlify.app/'
languageCode = 'en-us'
title = 'Sevebs Legal'
themesDir = "themes"
theme = 'sevens'
paginate = 10

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1

[[menu.main]]
    name = "ATTORNEYS"
    url = "/attorneys/"
    weight = 2

[[menu.main]]
    name = "CRIMINAL LAW"
    url = "/criminal/"
    weight = 3

[[menu.main]]
    name = "TESTIMONIALS"
    url = "/testimonials/"
    weight = 4

[[menu.main]]
    name = "BLOG"
    url = "/blog/"
    weight = 5

[[menu.main]]
    name = "CONTACT"
    url = "/contact/"
    weight = 6